version: '3.7'

services:
  kaholo-app:
    image: kaholo-app
    build:
      dockerfile: docker/Dockerfile-app
      context: .
    ports:
      - 80:80
    networks:
      - kaholo

  e2eTests:
    depends_on:
      - kaholo-app
    image: kaholo-e2e-tests
    build:
      dockerfile: docker/Dockerfile-cypress
      context: .
    volumes:
      - ./cypress/screenshots/:/e2e/screenshots/
      - ./cypress/reports/:/e2e/reports/
    command: npx cypress run
#    command: npm run cy:report
    networks:
      - kaholo

networks:
  kaholo:
    driver: bridge
    name: kaholo
    ipam:
      config:
        - subnet: 172.20.30.0/24

