FROM cypress/base:10
WORKDIR /e2e
COPY package.json .
COPY package-lock.json .
RUN npm i --silent
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list && \
    apt-get update && \
    apt-get install -y dbus-x11 google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*
COPY . .
